### ISSUE TITLE
Upgrade to IDEA 2017.3

### ISSUE THREAD

**Issue by davsclaus** [camel-idea-plugin/camel-idea-plugin#367] opened 2018-01-08 19:04 UTC

**Comment by bennetelli** [comment] 2018-01-09 09:05
I just tried to upgrade and it seems there are some changes in jar dependencies of IDEA. We will have to change our install.sh script and some other things.

**Comment by fharms** [comment] 2018-01-09 10:09
It's normal only necessary to change the install.sh script if the new jar files is located other places then "lib" or if there is a naming conflict between multiple jars, like resources_en.jar

**Comment by fharms** [comment] 2018-01-11 19:18
It's always a hazel upgrading the IDEA SDK, but this time it's a pain in the a..

**Comment by fharms** [comment] 2018-01-13 11:42
Next issue after upgrading 
`ERROR: Performance warning: LineMarker is supposed to be registered for leaf elements only, but got: PsiLiteralExpression:"jms:queue:myqueue?jmsKeyFormatStrategy=foo" (class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl) instead. First child: PsiJavaToken:STRING_LITERAL (class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl)
Please see LineMarkerProvider#getLineMarkerInfo(PsiElement) javadoc for detailed explanations.
java.lang.AssertionError: Performance warning: LineMarker is supposed to be registered for leaf elements only, but got: PsiLiteralExpression:"jms:queue:myqueue?jmsKeyFormatStrategy=foo" (class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl) instead. First child: PsiJavaToken:STRING_LITERAL (class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl)
Please see LineMarkerProvider#getLineMarkerInfo(PsiElement) javadoc for detailed explanations.
	at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:61)
	at com.intellij.testFramework.TestLogger.error(TestLogger.java:40)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.codeInsight.daemon.LineMarkerInfo.<init>(LineMarkerInfo.java:89)
	at com.intellij.codeInsight.daemon.MergeableLineMarkerInfo.<init>(MergeableLineMarkerInfo.java:52)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerInfo.<init>(RelatedItemLineMarkerInfo.java:47)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.createLineMarkerInfo(NavigationGutterIconBuilder.java:199)
	at org.apache.camel.idea.gutter.CamelRouteLineMarkerProvider.collectNavigationMarkers(CamelRouteLineMarkerProvider.java:130)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:40)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:213)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:120)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:107)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.Throwable: Performance warning: LineMarker is supposed to be registered for leaf elements only, but got: PsiLiteralExpression:"jms:queue:myqueue?jmsKeyFormatStrategy=foo" (class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl) instead. First child: PsiJavaToken:STRING_LITERAL (class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl)
Please see LineMarkerProvider#getLineMarkerInfo(PsiElement) javadoc for detailed explanations.`

**Comment by davsclaus** [comment] 2018-01-15 07:57
Ah crap, IDEA always have upgrade "fun"

**Comment by fharms** [comment] 2018-01-15 08:07
I'm down to the problem now is centered around CamelRouteLineMarkerProvider and a few unit tests

**Comment by bennetelli** [comment] 2018-01-15 10:19
sounds good +1

**Comment by davsclaus** [comment] 2018-01-16 17:37
There is a 2017.3.3 release out

**Comment by fharms** [comment] 2018-01-16 17:49
Are you kidding me

**Comment by bennetelli** [comment] 2018-01-16 17:51
:DDDDDDDDD can't stop laughing. Sorry Flemming :D

**Comment by fharms** [comment] 2018-01-21 15:03
@davsclaus @bennetelli please take look on https://github.com/camel-idea-plugin/camel-idea-plugin/pull/369 before I upgrade again to 2017.3.3 :-|

**Comment by davsclaus** [comment] 2018-01-21 18:56
Yeah it looks good

**Comment by davsclaus** [comment] 2018-01-22 08:21
Okay the #369 has now been merged, have fun with the next update ;)

**Comment by fharms** [comment] 2018-01-22 21:20
fixed in #370 
- roger over

**Closed by fharms** 2018-01-22 21:20 UTC
