### ISSUE TITLE
not work in idea 2017.1.2

### ISSUE THREAD

**Issue by abccbaandy** [camel-idea-plugin/camel-idea-plugin#306] opened 2017-05-12 02:59 UTC
I can see the camel icon but no popup when I write my endpoint, but it did check if any syntax wrong like unknown option.
Event log only said : Camel IDEA plugin is using camel-catalog version 2.19.0

IDEA : 2017.1.2
camel plugin : 0.4.0
camel : 2.19.0

**Comment by davsclaus** [comment] 2017-05-13 08:02
Can you maybe try other Camel examples or projects. For example the camel-example-console or camel-example-spring-boot from the Apache Camel release or the source code at: https://github.com/apache/camel/tree/master/examples

And is this the first time you use the plugin, or have you used previously where it worked for you.

**Comment by abccbaandy** [comment] 2017-05-13 09:38
nope, same problem.
And no, this it first time I use this plugin.

Is there anything I need do to popup the hint? or it's default behavior?

**Comment by davsclaus** [comment] 2017-05-13 09:42
Take a look at the front page here with that animated picture that shows how it should work. Maybe try a similar project like that
https://github.com/camel-idea-plugin/camel-idea-plugin

**Comment by abccbaandy** [comment] 2017-05-13 09:49
ya, I know that gif, but it just didn't pop up anything when I typing. I also try to press ctrl + space too.

**Comment by davsclaus** [comment] 2017-05-13 10:10
I dont know what is wrong on your end. Here is works, downloaded Camel 2.19 and unzip/untar it, and go into its examples directory and loaded the camel-example-spring-boot. Added a `?` in the 'stream:out` endpoint and pressed `ctrl + space`, see below
![screen shot 2017-05-13 at 12 08 57 pm](https://cloud.githubusercontent.com/assets/477100/26024609/18ffa7f4-37d5-11e7-8fab-61322a33d6fb.png)

**Comment by abccbaandy** [comment] 2017-05-13 10:39
ok, hope someone can figure out what happen.

**Comment by davsclaus** [comment] 2017-05-23 09:07
Closing as cannot reproduce

**Closed by davsclaus** 2017-05-23 09:07 UTC
